### ISSUE TITLE
Let all functions return `error`, instead of `panic`ing ? 

### ISSUE THREAD

**Issue by hitoshi44** [scru128/go-scru128#1]
Hello! I read your tweet-tree on UUID draft working, and I am exited to explore this repository!

In Golang, it's more popular to return `error` than  `panic`ing, especially for a large application. 
So it seems better to let functions which may panic return error.

If you confirm this issue is actually meaningful, please check a PR which I send later.

**Comment by hitoshi44** [comment]
My working done. Now I wonder that I can PR directly to main branch... because library's usage changed a little. It seems this repository do versioning. 

The branch is [here](https://github.com/hitoshi44/go-scru128/tree/feature/panic_to_error). Thank you.

**Comment by LiosK** [comment]
Thank you for your comments!

`New()` and `NewString()` panic on error for the convenience of users because, in common environments, random number generators almost never fail. Developers concerned about errors can still call `Generate()` of `Generator` directly.

`GenerateCore()` and `FromFields()` panic on invalid arguments because such inputs usually represent some bugs that should be fixed, rather than handled as an error. Panic here is like an AssertionError and should not be recovered.

**Comment by hitoshi44** [comment]
Thank you for your replying!

I may see your points. When I want to avoid `panic`, I can use `Generate()` to get `Id`.  
And yes, as long as using `Generate()`, whether it may panic or not is perfectly controllable by a careful developer. Thus using it will not be a problem.

But in case we use `New()` and `NewString()`, there a chance to panic is not zero. So using these 2 methods for a large application seems uneasy for me (Excuse me for sticking it. )

Is this "unrecoverable" approach is ordinary for UID library?

**Comment by LiosK** [comment]
I followed the design of this: https://pkg.go.dev/github.com/google/uuid

**Comment by hitoshi44** [comment]
I read it, and `panic` sometimes appears. It seems not a big problem to use `panic` on some particular point.
Thank you for your sharing, it was informative and helpful for me.

Here is my understanding by reading the source.
 - `Version1` has only 1 method `NewUUID` to generate an uuid, and it may `panic`.
 - `Version4` has 3 methods to gen.
   - `New()`, `NewString()` may `panic`, are the same to `scru128/New()`, `scru128/NewString()`.
   - still, `NewRandom()` does Not panic.

**Comment by LiosK** [comment]
`NewUUID()` returns error on failure, according to the signature.

**Comment by hitoshi44** [comment]
Inside `NewUUID`, `randomBits` is called which may panic when it fail to read from /dev/urandom.
And as you told me, using `panic` on failure to read from OS RNG stuff. It is new to me! Thank you.

Should I close this issue?
